### ISSUE TITLE
Bug: Not able to install on alpine linux

### ISSUE THREAD

**Issue by pascallap** [1Password/secrets-orb#16]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Invoking the install-cli command on alpine will result with: `Cannot determine OS type. Exiting...`

### Minimum reproduction config

```
version: 2.1
setup: true
orbs:
  1password: onepassword/secrets@1.0.0

jobs:
    demo:
        docker:
            image: alpine:latest
        steps:
            - 1password/install-cli
workflows:
  demo:
    jobs:
        - demo
```

### Other

Alpine is supported since version 2.0.1 of the onepassword cli.

It should be available for install with this orb.
